### ISSUE TITLE
Stability Test Failure

### ISSUE THREAD

**Issue by kiritigowda** [kiritigowda/MIVisionX-Validation-Tool#15]
The Tool does not run in the loop for long time, it fails abruptly.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 look into this issue in RALI & Inference modules.

**Comment by kiritigowda** [comment]
@hansely & @LakshmiKumar23 
 
With Version 1.0 - the memory usage grows over the span of the looping and finally crashes when the memory usage reaches 90%

The two main bugs that are concerning us now are
* Memory leak
* System Setup

**Comment by hansely** [comment]
Solved in develop branch
