### ISSUE TITLE
Version 0.01 

### ISSUE THREAD

**Issue by kiritigowda** [kiritigowda/MIVisionX-Validation-Tool#3]
* Required end to end solution to run batch size 16
* Basic GUI
* Basic ADAT

**Comment by kiritigowda** [comment]
@hansely & @LakshmiKumar23 can we have this checked in soon?

**Comment by LakshmiKumar23** [comment]
@kiritigowda ADAT and end to end for batch size 16 is complete

**Comment by kiritigowda** [comment]
Version 0.01 Released with PR #7
